### ISSUE TITLE
Installation instructions don't work, no src/prisma/schema.prisma

### ISSUE THREAD

**Issue by jbrucker** [Cobda/cobda-web#72]
Step 4 of the sparsely written installation instructions fail because
there is no file src/prisma/schema.prisma

I tried this on both the development and master branches.

**Comment by LilBank** [comment]
I have to apologize for our unclear instructions, the **step 4** now only works on the `pre-development` branch. This branch is the branch that contains the latest commits. Please kindly switch to `pre-development`.

P.S. We will merge the branch into `development` once we take a re-visit.
